from turtle import Turtle, colormode, done

person_turtle: Turtle = Turtle()
person_turtle.penup()
person_turtle.pencolor("brown")
person_turtle.goto(100, 100)
person_turtle.pendown()
person_turtle.right(90)
person_turtle.forward(50)
person_turtle.left(30)
person_turtle.forward(20)
person_turtle.right(180)
person_turtle.forward(20)
person_turtle.left(120)
person_turtle.forward(20)
person_turtle.right(180)
person_turtle.forward(20)
person_turtle.left(30)
person_turtle.forward(40)
person_turtle.right(90)
person_turtle.forward(20)
person_turtle.right(180)
person_turtle.forward(40)
person_turtle.penup()
person_turtle.goto(100, 120)
person_turtle.pendown()
person_turtle.circle(10)
done()